name: Publish to NPM and JSR
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nodejs
        with:
          registry-url: https://registry.npmjs.org/
      - name: Build and create jsr.json
        run: |
          pnpm build
          pnpm create-jsr

      - name: Publish to NPM
        if: "!github.event.release.prerelease"
        run: pnpm publish --access public --provenance

      - name: Publish to NPM with 'next' tag
        if: "github.event.release.prerelease"
        run: pnpm publish --access public --provenance --tag next

      - name: Publish to JSR
        run: pnpm exec jsr publish
