name: Tests

on:
  pull_request:

jobs:
  lint_and_type_check_and_test:
    name: Lint, type check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nodejs
      - name: Lint
        run: |
          pnpm lint
          pnpm -C=playground lint
      - name: Type check
        run: |
          pnpm -C=playground check
          pnpm check
      - name: Test
        # TODO
        run: echo TODO
